#!/bin/bash
user=
pass=
server=https://video.technion.ac.il
cookie_file=cookie

function usage {
    echo Usage: $0 COURSE_PAGE [FIRST_VIDEO_NUM [LAST_VIDEO_NUM]]
}
# Check url format
if [[ $1 != https://video.technion.ac.il/Courses/*.html ]]; then
	echo 'Error: please insert valid course url (e.g https://video.technion.ac.il/Courses/PhysMech.html).'
    usage
	exit
fi;

# Get username and password from user
if [[ -z $user ]]; then
    read -p "Username: " user
fi;
if [[ -z $pass ]]; then
    read -s -p "Password: " pass
fi;

# Check url validity
curl -s -b $cookie_file  $1 >/dev/null
if [[ $? -ne 0 ]]; then
	echo 'Error: please insert exists course url (e.g http://video.technion.ac.il/Courses/PhysMech.html).'
	exit 1
fi;

# Calculate the number of all the videos
videos=`curl -s -b $cookie_file $1 | grep -a movies/rtsp -c`

# Check video numbers
if (( $# >= 2 )) ; then
	if ! [[ "$2" =~ ^[0-9]+$ ]]  || (( $2 == 0 )) ; then
		echo 'Error: the second & third parameter can be only positive numbers.'
		exit 1
	fi;
	if (( $2 > $videos )) ; then
		echo Error: there are just $videos videos, begin index $2 is too high
		exit 1
	fi;
fi;

if (( $# == 3 )) ; then
	if ! [[ "$3" =~ ^[0-9]+$ ]] || (( $3 == 0 )) ; then
		echo 'Error: the second & third parameter can be only positive numbers.'
		exit 1
	fi;
	if  (( $3 > $videos )) ; then
		echo Error: there is just $videos videos, end index $3 is too high.
		exit 1
	fi;
	if (( $3 < $2 )) ; then
		echo Error: end index $3 is higher than begin index $2
		exit 1
	fi;
fi;

# Let's rock!
curl -s -b $cookie_file $1 | grep -a movies/rtsp | cut -d"'" -f4 | head -n ${3-$videos} | tail -n +${2-1} |
    while read line; do
        echo Downloading `echo $line | cut -d"/" -f6`, please wait...
        msdl -s2 `curl -s -b $cookie_file $server$line | grep -a 'window.location="rtsp' | cut -d"\"" -f2 ` -o `echo $line | cut -d"/" -f6`
    done
